### PR TITLE
swipe support

### PR DESCRIPTION
**Pull request by qwiglydee**

### CODE REVIEW

**Comment by juank11memphis** [comment]
Thanks a lot @qwiglydee, merging now!

**Comment by MadJlzz** [comment]
I think there is a mistake in the code :
md-swipe-left="ctrl.navigateRight()"
md-swipe-right="ctrl.navigateLeft()

The mapping are reversed, aren't they?

**Comment by qwiglydee** [comment]
Nope.
When you swipe current slide to left, you are to reveal slide at right.

**Comment by MadJlzz** [comment]
I didn't test since I am on my phone but when I read that I found it strange. Thanks for the explanation :+1

**Comment by qwiglydee** [comment]
@MadJlzz but this feature is indeed for phones!

**Comment by MadJlzz** [comment]
@qwiglydee I meant I was reading your code on my phone and not testing it. My bad.

**Comment by U-like** [comment]
This is essential, so thanks to @qwiglydee for th PR.
And thanks @juank11memphis for this carousel.

I noted that this PR missed to upgrade the **dist** files. I'm I right or I'm missing something?

Thanks!

**Pull request merged**
